apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: local-zfs-provisioner
  namespace: kube-system
  labels:
    app: local-zfs-provisioner
    tier: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-zfs-provisioner
  template:
    metadata:
      labels:
        app: local-zfs-provisioner
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: local-zfs-provisioner
      serviceAccount: local-zfs-provisioner
      containers:
      - name: local-zfs-provisioner
        image: asteven/local-zfs-provisioner:v0.0.1
        imagePullPolicy: Always
        args:
        - --debug
        - controller
        - --dataset-mount-dir=/var/lib/local-zfs-provisioner
        - --config=/etc/config/config.json
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config/
          readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: local-zfs-provisioner-config
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-zfs
provisioner: asteven/local-zfs
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
